apiVersion: v1
kind: Service
metadata:
  name: whoami-service-lb
  namespace: default
  annotations:
    metallb.io/ip-allocated-from-pool: mikrotik  # If using a specific MetalLB IP pool
    external-dns.alpha.kubernetes.io/hostname: whoami.cluster.mycdndomain.us
spec:
  type: LoadBalancer
  selector:
    app: whoami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalTrafficPolicy: Local  
