---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-config-reader
  namespace: traefik
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-config-reader-binding
  namespace: traefik
subjects:
  - kind: ServiceAccount
    name: default  # or replace with your service account name
    namespace: traefik
roleRef:
  kind: Role
  name: traefik-config-reader
  apiGroup: rbac.authorization.k8s.io
